source_code:
  - 'src/*.java'
tests:
  - 'tests/*.java'
  - 'tests/*.py'
workflows:
  - '.github/workflows/**'
example:
  - 'example.sumatra'
libraries:
  - 'sumatra/*.sumatra'
documentation:
  - '*.md'
  - '**/*.md'
