name: Changes
on:
  workflow_call:
    outputs:
      source_code:
        value: ${{ jobs.changed.outputs.source_code }}
      tests:
        value: ${{ jobs.changed.outputs.tests }}
      workflows:
        value: ${{ jobs.changed.outputs.workflows }}
      example:
        value: ${{ jobs.changed.outputs.example }}
      libraries:
        value: ${{ jobs.changed.outputs.libraries }}
      documentation:
        value: ${{ jobs.changed.outputs.documentation }}

jobs:
  changed:
    name: Changed
    runs-on: ubuntu-latest
    outputs:
      source_code: ${{ steps.filter.outputs.source_code }}
      workflows: ${{ steps.filter.outputs.workflows }}
      example: ${{ steps.filter.outputs.example }}
      libraries: ${{ steps.filter.outputs.libraries }}
      documentation: ${{ steps.filter.outputs.documentation }}
      tests: ${{ steps.filter.outputs.tests }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        show-progress: false
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: .github/path-filters.yaml
        token: ${{ github.token }}
